apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pizzas.stable.mycorp.com
spec:
  group: stable.mycorp.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ingredients:
                  type: array
                  items:
                    type: string
                price:
                  type: integer
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: pizzas
    singular: pizza
    kind: Pizza
    shortNames:
    - pz

